
apiKey: IoVV8jaWtJX5CRRIYqyR542r9Q2SzvU17XCDZun8
#apiBaseUrl: https://exercise.trunarrative.cloud/TruProxyAPI/rest
apiBaseUrl: http://localhost:8090

server:
  port: 8090
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#  servlet:
#    multipart:
#      enabled: false
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5436/companies_database?createDatabaseIfNotExist=true
#    username: user
#    password: 123456

